[build]
  functions = "netlify/functions"
  publish = "build"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[scheduled]]
  path = "/.netlify/functions/twitch"
  schedule = "*/30 * * * *" # 
