[build]
  functions = "netlify/functions"
  publish = "build"

[[functions]]
  name = "twitch"
  schedule = "*/30 * * * *"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
