[build]
  functions = "netlify/functions"
  publish = "build"

[functions]
  included_files = ["netlify/data/*.json"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[functions."twitch"]
  schedule = "*/30 * * * *"
