[build]
  publish = "build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."twitch"]
  schedule = "*/15 * * * *" # Toutes les 15 min

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
