[build]
  publish = "build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."twitch"]
  schedule = "*/15 * * * *" # Toutes les 15 min
  included_files = [
    "netlify/functions/data/streamers.json",
    "netlify/functions/data/streamers_cache.json",
    "netlify/functions/data/.twitch_token.json"
  ]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
